### ISSUE TITLE
Select all toggle, selects ALL items in BC Box (including not visible items on other pages)

### ISSUE THREAD

**Issue by Chris82933** [bcgov/bcbox#112]
#### Describe the bug
When you toggle the "select all" radio button, it selects all the items on the BC Box bucket. Applying any action to this selection applies it to everything in the bucket.

ie. Deleting (a page of items) deletes all the items in the bucket

#### Expected behavior
Apply action to the selected items on the current page (not the entire bucket)
This would match the UX of other sites, as to not delete items that are not visible on the current page

**Comment by TimCsaky** [comment]
I agree. when you check the 'select all' box, I would prefer only the visible rows be selected.
It looks like there is an option for this with our datatable component: https://primevue.org/datatable/#checkbox_row_selection.
