### ISSUE TITLE
Upload Fails (False complete notification)

### ISSUE THREAD

**Issue by Chris82933** [bcgov/bcbox#113]
#### Describe the bug
Uploading a file fails. Consistently fails, I have tried 3 times.

#### To Reproduce

Test File: https://releases.ubuntu.com/22.04.3/ubuntu-22.04.3-desktop-amd64.iso
I am currently using the above file but I have many other zip files to test with.

Uploading this Ubuntu ISO triggers "Complete" notification but fails to upload. The file is not presented in BC Box or in our bucket (checking using S3 Browser).

#### Screenshots
![image](https://github.com/bcgov/bcbox/assets/7146032/93434aa9-7783-4ebe-969c-30d1c4aa4198)

#### Desktop (please complete the following information):
I am uploading from local disk C to BC Box using a remote desktop via citrix.

**Comment by Chris82933** [comment]
Completed further testing. 3gb file uploads are more consistently successful. 5gb file continues to fail.

**Comment by TimCsaky** [comment]
@Chris82933 Chris. we've made some changes to our COMS api to support large file uploads and would love to see if things work better for you now. I can get in touch next week. thanks

**Comment by jujaga** [comment]
Root cause identified and resolved in https://github.com/bcgov/common-object-management-service/pull/216
