### ISSUE TITLE
Adding Object Permissions Fails

### ISSUE THREAD

**Issue by danebenal** [bcgov/bcbox#123]
#### Describe the bug
Adding permissions on an object fails with an AxiosError: Request failed with status code 422

#### To Reproduce

1. Open a Bucket with an Object
2. Click the Object Permissions button
3. Add a permission to a user

#### Expected behavior
Permission should be added without an error.

#### Screenshots
<img width="779" alt="Screenshot 2023-09-14 102317" src="https://github.com/bcgov/bcbox/assets/6244673/ae49ef56-4528-4b44-b127-742d36697a44">
<img width="548" alt="Screenshot 2023-09-14 102433" src="https://github.com/bcgov/bcbox/assets/6244673/c95790e4-fee7-4563-972d-5ec4045a00b8">
<img width="626" alt="Screenshot 2023-09-14 102412" src="https://github.com/bcgov/bcbox/assets/6244673/5d0ea2b8-60e5-43d6-9bd4-c11773e11543">

#### Desktop (please complete the following information):

- OS: Windows 10
- Browser: Edge 
- Version: 116.0.1938.81

**Comment by jujaga** [comment]
Known issue in COMS that just got a hotfix: https://github.com/bcgov/common-object-management-service/pull/209
