### ISSUE TITLE
Object Ids are Cached after Deletion

### ISSUE THREAD

**Issue by danebenal** [bcgov/bcbox#127]
#### Describe the bug
After deleting a file using the checkbox and delete button at the top and subsequently trying to download or delete using the top buttons cause errors as BCBox is trying to download/delete the original object id.

#### To Reproduce

1. Go to a bucket
2. Upload a file
3. Select the checkbox to the left of the file name
<img width="272" alt="image" src="https://github.com/bcgov/bcbox/assets/6244673/1c59d3b8-1b73-4b22-a33f-d313fa33a043">

4. Use the Delete button at the top (next to the Upload and Download buttons)
5. File is deleted
6. Use the Download or Delete buttons at the top
7. Error is encountered

Trying to download a file after deleting it: ![image](https://github.com/bcgov/bcbox/assets/6244673/93e55a48-1d68-4308-8995-ac46cbcf78b8)
Trying to delete a file after deleting it: 
- ![image](https://github.com/bcgov/bcbox/assets/6244673/45e18007-9d9f-420f-9f75-ed544b27d843)
- ![image](https://github.com/bcgov/bcbox/assets/6244673/2c3a65c5-e3a4-4d43-8569-53d5d13e4566)

#### Expected behavior
The Download and Delete buttons should not retain previous Object Ids after they have been deleted.

#### Desktop (please complete the following information):

- OS: Windows 10
- Browser: Edge 
- Version: 117.0.2045.31

**Comment by slhurley** [comment]
Jira issue 3364

**Comment by jujaga** [comment]
Resolved in #136
