### ISSUE TITLE
"Application Readme" is missing

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/bcbox#94]
#### Describe the bug
The [main README.md](https://github.com/bcgov/bcbox/blob/master/README.md) document referes to an "Application README.md".  However, when I click the Application README.md link, I get a 404.  Additionally, when I search the entire project for README.md files, I only see a frontend one, not an Application README.

Thank you.

#### To Reproduce

1. Go to 'https://github.com/bcgov/bcbox/blob/master/README.md'
2. Click on 'Application README link'
3. See 404

#### Expected behavior
An application specific README

#### Desktop (please complete the following information):

Mac OSX, Chrome

**Comment by loneil** [comment]
I think this should just link to the `/frontend` readme, as that's really the "application" rather than the `/app` (node backend that just serves it) @jujaga @TimCsaky ?
